[package]
name = "resp3"
description = "RESP3 protocol implementation"
authors = ["Evgeniy Terekhin <e_terekhin@pm.me>"]
license = "MIT"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "1"
nom = "7"
nom-regex = "0.2"
once_cell = "1"
regex = "1"
